Fix #149
MrPotatoBobx/FetchCord pull request #186
Opened 2021-11-22 10:46 UTC by SimPilotAdamT

Fixes #149 by altering the `boot_time()` function so that it works on UNIX-based OS's. Pulled the same function from PSUTIL for the Windows detection.

2021-11-22 15:03 UTC, Lukas-Batema requested changes
Could it change the `BootTime()` function to follow the "zen" of Python (like `boot_time()` was.

2021-11-22 15:21 UTC, SimPilotAdamT commented
> Could you change the `BootTime()` function to follow the "zen" of Python (like `boot_time()` was.

done

2021-11-22 15:25 UTC, Lukas-Batema commented
> > Could you change the `BootTime()` function to follow the "zen" of Python (like `boot_time()` was.
> 
> 
> 
> done

Thanks :), now it is up to BlivionIaG to review this.

2021-12-03 22:50 UTC, BlivionIaG approved these changes

2021-12-03 22:51 UTC, BlivionIaG approved these changes

2021-12-03 22:58 UTC, merged